### ISSUE TITLE
error on webpack

### ISSUE THREAD

**Issue by micuat** [topologicalmedialab/deep-performance-dwelling-monitor#2]
first, `webpack` is replaced by `webpack-cli`

also `webpack-cli` gives error (I'll paste error message tomorrow when I'm back to work)

**Comment by micuat** [comment]
current `package.json` / `webpack.config.js` files won't work with latest webpack (4.1.1). `loader` should be `rules` and `file-loader` needs update. Instead I will try installing old version of webpack

**Comment by micuat** [comment]
compatible webpack version is
```
npm install webpack@2.7.0
```

**Comment by jansensan** [comment]
Made a PR for this issue: https://github.com/topologicalmedialab/deep-performance-dwelling-monitor/pull/5
